dialog.editmartialart.title=Learned techniques in %s
dialog.editmartialart.techniques.selected=Selected

dialog.editsignature.listview.placeholder=Add cool combos of Edge actions and boosts here and connect them with a quality

dialog.editsignature.dialog.title=Define your signature move
dialog.editsignature.label.whenPerformingA=When performing a
dialog.editsignature.label.test=test,
dialog.editsignature.label.combine=combine
dialog.editsignature.label.and=and
dialog.editsignature.label.nameThis=and name this
dialog.editsignature.prompt.name=Crazy Ivan

dialog.editsignature.label.warning.format=You need to connect this with a '%s' quality
