package de.rpgframework.shadowrun6.items;

/**
 * @author prelle
 *
 */
public enum AmmunitionClass {

	/** Holdout/Light Pistol/Machine Pistol */
	LIGHT,
	/** Heavy Pistol/SMG */
	HEAVY,
	RIFLES,
	TASER,
	INJECTION_DART,
	ASSAULT_CANNON,
	ASSAULT_CANNON_B25,
	ASSAULT_CANNON_B30,
	ASSAULT_CANNON_B40,
	ASSAULT_CANNON_B50,
	ASSAULT_CANNON_B60,
	ASSAULT_CANNON_B75,
	ASSAULT_CANNON_B90,
	MORTAR_M40,
	MORTAR_M60,
	MORTAR_M80,
	MORTAR_M120,
	MORTAR_M160,
	CANNON_105,
	CANNON_120,
	CANNON_130,
	CANNON_140,
	ARTILLERY_A105,
	ARTILLERY_A155,
	ARTILLERY_A203,
	RAILGUN, //currently not used as small railguns use base ammo with ammotype railgun
	RAILGUN_LK1,
	RAILGUN_LK2,
	RAILGUN_LK3,
	RAILGUN_LK4,
	RAILGUN_LK5,
	RAILGUN_LK7,
	RAILGUN_LK8,
	RAILGUN_LK10,
	MACHINE_GUN,
	DMSO,
	SHOTGUN,
	BATTERY,
	FUEL,
	FOAM
}
