/**
 *
 */
package de.rpgframework.shadowrun6.items;

import java.util.List;

import de.rpgframework.shadowrun6.Shadowrun6Core;

/**
 * @author prelle
 *
 */
public enum ItemSubType {

	// BIOWARE
	BIOWARE_COSMETICS,
	BIOWARE_STANDARD,
	BIOWARE_CULTURED,
	BIOWARE_IMPLANT_WEAPON,
	SYMBIONTS,
	// Weapon
	CLUBS,
	BLADES,
	WHIPS,
	UNARMED,
	OTHER_CLOSE,
	BOWS,
	CROSSBOWS,
	THROWING,
	TASERS,
	HOLDOUTS,
	PISTOLS_LIGHT,
	PISTOLS_HEAVY,
	MACHINE_PISTOLS,
	SUBMACHINE_GUNS,
	SHOTGUNS,
	RIFLE_ASSAULT,
	RIFLE_HUNTING,
	RIFLE_SNIPER,
	LMG,
	MMG,
	HMG,
	ASSAULT_CANNON,
	OTHER_FIREARM,
	LAUNCHERS,
	THROWERS,
	OTHER_SPECIAL,
	WEAPON_ACCESSORY,
	EXPLOSIVES,
	WEAPON_SECURITY,
	// AMMUNITION,
	AMMUNITION,
	AMMO_TASER,
	AMMO_LIGHT,
	AMMO_HEAVY,
	AMMO_RIFLES,
	AMMO_MACHINE_GUN,
	AMMO_DARTS,
	AMMO_DMSO,
	AMMO_CANNONS,
	GRENADES,
	ROCKETS,
	MISSILES,
	// ARMOR
	ARMOR_BODY,
	ARMOR_HELMET,
	ARMOR_SHIELD,
	// Cyberware
	CYBER_COSMETICS,
	CYBER_HEADWARE,
	CYBER_EYEWARE,
	CYBER_EARWARE,
	CYBER_BODYWARE,
	CYBER_LIMBS,
	CYBER_LIMB_ENHANCEMENT,
	CYBER_LIMB_ACCESSORY,
	CYBER_IMPLANT_WEAPON,
	// TOOLS
	TOOLS,
	// Electronic
	LIVING_PERSONA,
	CYBERDECK,
	RIGGER_CONSOLE,
	COMMLINK,
	ELECTRONIC_ACCESSORIES,
	RFID,
	COMMUNICATION,
	ID_CREDIT,
	IMAGING,
	OPTICAL,
	AUDIO,
	SENSOR_HOUSING,
	SECURITY,
	BREAKING,
	TAC_NET,
	//
	CORE,
	CASES,
	CASE_MODS,
	CORE_OPTIONAL,
	// Software
	BASIC_PROGRAM,
	HACKING_PROGRAM,
	RIGGER_PROGRAM,
	AUTOSOFT,
	SKILLSOFT,
	TACNET_PROGRAM,
	OTHER_PROGRAMS,
	// Accessories
	ACCESSORY,
	MODIFICATION,
	VISION_ENHANCEMENT,
	AUDIO_ENHANCEMENT,
	SENSOR,
    // Chemicals
	INDUSTRIAL_CHEMICALS,
	TOXINS,
	DRUGS,
	BTL,
	// Survival
	SURVIVAL_GEAR,
	GRAPPLE_GUN,
	// Biology
	BIOTECH,
	SLAP_PATCHES,
	// Magical
	FOCI_ENCHANTING,
	FOCI_METAMAGIC,
	FOCI_POWER,
	FOCI_QI,
	FOCI_SPELL,
	FOCI_SPIRIT,
	FOCI_WEAPON,
	MAGICAL_FORMULA,
	MAGICAL_SUPPLIES,
	// Vehicles
	BIKES,
	ATVS,
	CARS,
	TRUCKS,
	VANS,
	BUS,
	TRACKED,
	SPECIAL_VEHICLES,
	HOVERCRAFT,
	PWC,
	BOATS,
	SHIPS,
	SUBMARINES,
	FIXED_WING,
	ROTORCRAFT,
	VTOL,
	LAV,
	LTAV,
	GRAV,
	WALKER,
	SPACECRAFT,
	VEHICLE_ACCESSORY,
	MOD_TRAILER,	
	// START: for backward compatability
	MICRODRONES,
	MINIDRONES,
	SMALL_DRONES,
	MEDIUM_DRONES,
	LARGE_DRONES,
	// END: for backward compatability
	// Drones
	GROUND,
	ANTHRO,
	AIR,
	AQUATIC,
	// Vehicle Modifications
	TIRES,
	MOD_LAYOUT,
	MOD_CORE,
	MOD_HANDLING,
	MOD_INTERIOR,
	MOD_CARGO,
	MOD_FORM,
	MOD_ARMOR,
	MOD_ELEMENTS,
	MOD_ACC,
	MOD_EFFICIENCY,
	MOD_SPEED,
	MOD_COAT,
	MOD_MISC,
	MOD_PILOT,
	MOD_MOUNT,
	MOD_RACK,
	MOD_OTHERS,
	MOD_PROPULSION,
	// Nanoware
	NANOWARE_HARD,
	NANOWARE_SOFT,
	NANO_CYBERWARE,
	NANOTECH_EQUIPMENT,
	// Gentech
	GENOM_CHANGES,
	EXOTIC_METAGENETICS,
	TRANSGENETICS,
	MICRO_ENVIRONADAPT,
	COMPLEMENTAL_GENETICS, 
	// PACKS
	COMPLETE_PACK
    ;
	
	//-------------------------------------------------------------------
	public String getName() {
		return Shadowrun6Core.getI18nResources().getString("itemsubtype."+this.name().toLowerCase());
	}

	public static List<ItemSubType> matrixDevices() { return List.of(COMMLINK, CYBERDECK, RIGGER_CONSOLE. TAC_NET);}
}
