image: maven:3.8.6-openjdk-18

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and test
          script:
            - mvn -B -s settings.xml clean install -DskipTests=true
  default:
    - step:
        script: 
          - mvn -B -s settings.xml clean deploy
    - step:
        name: Deploy to Staging
        deployment: Staging
        trigger: manual
        caches:
          - maven
        script:
          - cd Commlink6 ; mvn -B -s settings.xml clean package
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates'
              LOCAL_PATH: 'target/commlink6*fat.jar'
