image: maven:3.8.6-openjdk-18

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and test
          script:
            - mvn -U -B -s settings.xml clean install
  default:
    - step:
        caches:
         - maven
        script: 
          - mvn help:active-profiles
          - mvn -U -B -s settings.xml clean deploy -Dtype=develop -P desktop
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/develop'
              LOCAL_PATH: 'Commlink6/target/config.xml'
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/develop'
              LOCAL_PATH: 'Commlink6/target/commlink6*fat.jar'
        artifacts:
          - Commlink6/target/commlink6-*fat.jar
    - step:
        name: Deploy to Staging
        deployment: Staging
        trigger: manual
        caches:
         - maven
        script:
          - cd Commlink6; mvn -U -B -s settings.xml update4j:create -Dtype=testing -P desktop ; cd ..
          - ls Commlink6/target
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/testing'
              LOCAL_PATH: 'Commlink6/target/config.xml'
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/testing'
              LOCAL_PATH: 'Commlink6/target/commlink6*fat.jar'
    - step:
        name: Deploy to Production
        deployment: Production
        trigger: manual
        script:
          - cd Commlink6; mvn -B -s settings.xml update4j:create -Dtype=testing -Pdesktop ; cd ..
          - ls Commlink6/target
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/stable'
              LOCAL_PATH: 'Commlink6/target/config.xml'
          - pipe: atlassian/scp-deploy:1.2.1
            variables:
              USER: bitbucket
              SERVER: eden.rpgframework.de
              REMOTE_PATH: '/var/www/html/commlink6-updates/stable'
              LOCAL_PATH: 'Commlink6/target/commlink6*fat.jar'
