<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.rpgframework</groupId>
	<artifactId>shadowrun6-master</artifactId>
	<version>0.0.2-SNAPSHOT</version>
	<name>Shadowrun6 Master</name>
	<packaging>pom</packaging>

	<developers>
		<developer>
			<name>Stefan Prelle</name>
			<email>stefan@prelle.org</email>
			<timezone>GMT+1</timezone>
			<roles>
				<role>Lead developer</role>
			</roles>
		</developer>
	</developers>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<log4j.version>2.19.0</log4j.version>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.compiler.source>17</maven.compiler.source>
		<revision>0.0.2-SNAPSHOT</revision>
		<rpgfw.version>5.1.4-SNAPSHOT</rpgfw.version>
	</properties>

	<modules>
		<module>SR6_Core</module>
		<module>SR6_Data</module>
		<module>SR6_CharGen</module>
		<module>SR6_CharGen_JFX</module>
		<module>SR6_Foundry_VTT</module>
		<module>SR6_Export_JSON</module>
		<module>SR6_Export_FVTT</module>
		<module>Commlink6</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.prelle</groupId>
				<artifactId>simple-persist</artifactId>
				<version>3.5.0</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-core</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-rules</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-javafx</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-core</artifactId>
				<version>0.0.3-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-chargen</artifactId>
				<version>0.0.3-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-chargen-jfx</artifactId>
				<version>0.0.3-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-core</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-data</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-chargen</artifactId>
				<version>${revision}</version>
			</dependency>

		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-api</artifactId>
			   <version>${log4j.version}</version>
		   </dependency>
		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-core</artifactId>
			   <version>${log4j.version}</version>
			   <scope>runtime</scope>
		   </dependency>
		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-jpl</artifactId>
			   <version>${log4j.version}</version>
			   <scope>runtime</scope>
		   </dependency>
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<scope>test</scope>
				<version>4.13</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
		</repository>
	</distributionManagement>

	<ciManagement>
		<system>Bitbucket Pipelines</system>
		<url>https://bitbucket.org/rpgframework-cloud/shadowrun-common/pipelines/</url>
	</ciManagement>
	<scm>
		<connection>scm:git:git@bitbucket.org:rpgframework-cloud/shadowrun-common.git</connection>
		<developerConnection>scm:git:git@bitbucket.org:rpgframework-cloud/shadowrun-common.git</developerConnection>
		<url>https://bitbucket.org/rpgframework-cloud/shadowrun-common/</url>
		<tag>HEAD</tag>
	</scm>

	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
			</plugin>
		</plugins>
	</build>

</project>