<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.rpgframework</groupId>
	<artifactId>shadowrun6-master</artifactId>
	<version>0.0.3-SNAPSHOT</version>
	<name>Shadowrun6 Master</name>
	<packaging>pom</packaging>

	<developers>
		<developer>
			<name>Stefan Prelle</name>
			<email>stefan@prelle.org</email>
			<timezone>GMT+1</timezone>
			<roles>
				<role>Lead developer</role>
			</roles>
		</developer>
	</developers>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<log4j.version>2.24.3</log4j.version>
		<maven.compiler.target>23</maven.compiler.target>
		<maven.compiler.source>23</maven.compiler.source>
		<revision>0.0.3-SNAPSHOT</revision>
		<rpgfw.version>5.3.2-SNAPSHOT</rpgfw.version>
		<maven.deploy.skip>false</maven.deploy.skip>
	</properties>

	<modules>
		<module>SR6_Core</module>
		<module>SR6_Data</module>
		<module>SR6_CharGen</module>
		<module>SR6_CharGen_JFX</module>
		<module>SR6_Foundry_VTT</module>
		<module>SR6_Export_JSON</module>
		<module>SR6_Export_FVTT</module>
		<module>Commlink6</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.prelle</groupId>
				<artifactId>simple-persist</artifactId>
				<version>3.8.0</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-core</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-rules</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-javafx</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>rpgframework-generator</artifactId>
				<version>${rpgfw.version}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-core</artifactId>
				<version>0.0.4-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-chargen</artifactId>
				<version>0.0.4-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun-common-chargen-jfx</artifactId>
				<version>0.0.4-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-core</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-data</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-chargen</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>de.rpgframework</groupId>
				<artifactId>shadowrun6-chargen-jfx</artifactId>
				<version>${revision}</version>
			</dependency>

		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-api</artifactId>
			   <version>${log4j.version}</version>
		   </dependency>
		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-core</artifactId>
			   <version>${log4j.version}</version>
			   <scope>runtime</scope>
		   </dependency>
		   <dependency>
			   <groupId>org.apache.logging.log4j</groupId>
			   <artifactId>log4j-jpl</artifactId>
			   <version>${log4j.version}</version>
			   <scope>runtime</scope>
		   </dependency>
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<scope>test</scope>
				<version>4.13</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<ciManagement>
		<system>Bitbucket Pipelines</system>
		<url>https://bitbucket.org/rpgframework-cloud/shadowrun-common/pipelines/</url>
	</ciManagement>
	<scm>
  		<connection>scm:git:git://bitbucket.org/rpgframework-cloud/shadowrun6.git</connection>
 		<developerConnection>scm:git:ssh://bitbucket.org:rpgframework-cloud/shadowrun6.git</developerConnection>
  		<url>https://bitbucket.org/rpgframework-cloud/shadowrun6/src</url>
	</scm>


	<repositories>
		<repository>
         <name>Central Portal Snapshots</name>
         <id>central-portal-snapshots</id>
         <url>https://central.sonatype.com/repository/maven-snapshots/</url>
         <releases>
            <enabled>false</enabled>
         </releases>
         <snapshots>
            <enabled>true</enabled>
         </snapshots>
      </repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
			</plugin>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <version>3.3.0</version>
            <configuration>
               <excludes>**/module-info.java</excludes>
               <consoleOutput>true</consoleOutput>
               <failsOnError>true</failsOnError>
               <linkXRef>false</linkXRef>
               <checkstyleRules>
                  <module name="Checker">
                     <property name="localeCountry" value="DE"/>
                     <property name="localeLanguage" value="de"/>
                     <property name="fileExtensions" value="properties"/>
                     <module name="Translation"/>
                     <module name="TreeWalker">
                     </module>
                  </module>
               </checkstyleRules>
            </configuration>
            <executions>
               <execution>
                  <id>validate</id>
                  <phase>validate</phase>
                  <goals>
                     <goal>check</goal>
                  </goals>
               </execution>
            </executions>
      </plugin>
            <plugin>
               <groupId>org.sonatype.central</groupId>
               <artifactId>central-publishing-maven-plugin</artifactId>
               <version>0.7.0</version>
               <extensions>true</extensions>
               <configuration>
                  <publishingServerId>central</publishingServerId>
                  <deploymentName>${project.artifactId}_${project.version}</deploymentName>
                  <autoPublish>true</autoPublish>
               </configuration>
         </plugin>

		</plugins>
	</build>

</project>