label.spellcasting=Spellcasting
label.unarmed=Unarmed
label.edit=Edit
section.active_programs.device=Matrix Device
section.adeptpowers.ppTotal=Power Points:
section.adeptpowers.ppUnspent=Free:
section.adeptpowers.selector.title=Select a power to add
section.bodyplan.title=Bodyplan Configuration
section.bodyplan.armpairs=Armpairs
section.bodyplan.lowerbody=Lower Body
section.bodyplan.tail=Tail
section.combat.astral=Astral Combat
section.combat.attacks=Attacks
section.combat.damage=Resistance
section.combat.defensepools=Defense Pools
section.combat.fulldefense=Full Defense
section.combat.matrix.ar=AR
section.combat.matrix.device_monitor=Device Monitor
section.combat.matrix.vr=VR Cold
section.combat.matrix=Cybercombat
section.combat.matrixuv=Cybercombat UV Host
section.combat.modifications=Modifications
section.combat.physical=Combat
section.combat.ar=AR
section.combat.pool=Pool
section.critterpowers.title=Critter Power
section.datastructure.selector.title=Configure the data structure
section.emulated_programs.label=Emulated Programs learned as complex forms or via echo 'Software Emulator'
section.emulated_programs.cell.src_cform=from complex form
section.emulated_programs.cell.src_echo=Absorbed
section.martialarts.title=Martial Arts
section.martialarts.selector.title=Learn a new martial art
section.persona.defensePool=Defense Pool
section.persona.defenseRating=Defense Rating
section.rigging.title=Rigging
section.rigging.rig=Control rig
section.rigging.rcc=RCC
section.qualitypaths.selector.title=Select a Quality Path
section.qualitypaths.title=Quality Paths
section.software.title=Software Library
section.software.unused=Not installed
section.spark.title=Spark
section.spark.essHole=Spark hole
section.spark.essLost=Spark lost
section.spark.essRemain=Spark remaining
section.spark.neuromorphism.tooltip=Raise your grade (AIs only) to get a 1.0 essence hole.
section.spark.neuromorphism=Neurom. Grade

