label.spellcasting=Spellcasting
label.unarmed=Unarmed
section.active_programs.device=Matrix Device
section.adeptpowers.ppTotal=Power Points:
section.adeptpowers.ppUnspent=Free:
section.combat.astral=Astral Combat
section.combat.attacks=Attacks
section.combat.fulldefense=Full Defense
section.combat.initiative=Initiative
section.combat.matrix.ar=AR
section.combat.matrix.device_monitor=Device Monitor
section.combat.matrix.vr=VR Cold
section.combat.matrix=Cybercombat
section.combat.matrixuv=Cybercombat UV Host
section.combat.physical=Combat
section.combat.pool=Pool
section.martialarts.title=Martial Arts
section.martialarts.selector.title=Learn a new martial art
section.persona.defensePool=Defense Pool
section.persona.defenseRating=Defense Rating
section.qualitypaths.selector.title=Select a Quality Path
section.qualitypaths.title=Quality Paths
section.software.title=Software Library
section.software.unused=Not installed