section.active_programs.device=Matrix Device

section.adeptpowers.ppUnspent=Free:
section.adeptpowers.ppTotal=Power Points:

section.persona.defenseRating=Defense Rating
section.persona.defensePool=Defense Pool

section.qualitypaths.title=Quality Paths
section.qualitypaths.selector.title=Select a Quality Path


section.software.title=Software Library