label.mode.chargen=Creation Mode
label.mode.career=Career Mode

action.conversionIncrease=Convert more Karma to Nuyen
action.conversionDecrease=Convert less Karma to Nuyen

page.basicdata.title=Basic Data
page.basicdata.section.basic.title=Basic Data
page.basicdata.section.attributes.title=Attributes

gender.male=male
gender.female=female
gender.diverse=diverse

label.streetname=Streetname
label.realname=Real name
label.gender=Gender
label.metatype=Metatype
label.magicOrResonance=Magic/Resonance
label.heat=Heat

page.skills.title=Skills
page.skills.section.normal=Normal skills
page.skills.section.knowledge=Knowledge skills
page.skills.section.language=Languages
page.skills.section.signature=Signature Maneuvers

page.augmentation.title=Augmentation
page.augmentation.section.transhumanism=Transhumanism
page.augmentation.section.cyberware=Cyberware
page.augmentation.section.bioware=Bioware
page.augmentation.section.essence=Essence
page.augmentation.section.essence.acclimation=Acclimation Level
page.augmentation.section.essence.acclimation.tooltip=Change level of the "Augmentation Acclimation" quality.\nProvides 0.1 essence hole per level.
page.augmentation.section.essence.transhumanism=Transhum. Grade
page.augmentation.section.essence.transhumanism.tooltip=Raise your grade (mundanes only) to get a 1.0 essence hole.
page.augmentation.section.essence.essHole=Essence hole
page.augmentation.section.essence.essLost=Essence lost
page.augmentation.section.essence.essRemain=Essence remaining

page.combat.title=Combat
page.combat.section.ranged=Ranged Weapons
page.combat.section.melee=Melee Weapons
page.combat.section.armor=Armor & Clothing
page.combat.section.ammo=Ammunition

page.gear.section.electro=Electronics
page.gear.section.other=Other
page.gear.section.magical=Magical

page.magic.title=Magic
page.magic.section.adeptpowers=Adept Powers
page.magic.section.spells=Spells
page.magic.section.metamagic=Metamagic
page.magic.section.rituals=Rituals

page.matrix.title=Matrix
page.matrix.section.activePrograms=Active Programs
page.matrix.heading.device=Device
page.matrix.section.accessories=Accessories
page.matrix.section.persona=Persona
page.matrix.section.persona.defenseRating=Defense Rating
page.matrix.section.persona.defensePool=Defense Pool

page.resonance.title=Resonance
page.resonance.section.complexforms=Complex Forms
page.resonance.section.echoes=Submersion

page.vehicles.title=Vehicles
page.vehicles.section.vehicles=Vehicles
page.vehicles.section.drones=Drones

page.gear.title=Gear

page.life.title=Life
page.life.section.sins=SINs
page.life.section.contacts=Contacts
page.life.section.lifestyles=Lifestyles

page.career.title=Career

error.title=Drek
error.no_chargen_in_character=Missing info about chargen method
error.continuingCreation=Failed to open the character and continue creation.\n\
 This is a bug in the application you can report, but the character is likely beyond saving.
 
section.gear.selector.title=What do you want to add?