error.no_chargen_in_character=Missing info about chargen method
page.vehicles.section.drones=Drones
page.augmentation.section.essence.transhumanism.tooltip=Raise your grade (mundanes only) to get a 1.0 essence hole.
page.augmentation.section.bioware=Bioware
page.augmentation.section.essence.essLost=Essence lost
page.skills.section.normal=Normal skills
page.resonance.title=Resonance
page.resonance.section.echoes=Submersion
page.basicdata.section.basic.title=Basic Data
page.life.section.contacts=Contacts
label.reputation=Reputation
page.career.title=Career
page.basicdata.title=Basic Data
label.streetname=Streetname
page.combat.section.armor=Armor & Clothing
page.augmentation.section.essence.essRemain=Essence remaining
page.vehicles.title=Vehicles
section.gear.selector.title=What do you want to add?
page.magic.section.spells=Spells
label.metatype=Metatype
section.creation.title=Creation Info
page.resonance.section.complexforms=Complex Forms
page.career.reward.add.title=Tell me about your run, chummer!
page.life.section.sins=SINs
page.matrix.section.activePrograms=Active Programs
page.gear.title=Gear
page.augmentation.section.essence.transhumanism=Transhum. Grade
page.gear.section.electro=Electronics
page.gear.section.magical=Magical
page.magic.section.rituals=Rituals
page.matrix.title=Matrix
page.matrix.section.devices=Devices
page.combat.title=Combat
page.augmentation.section.transhumanism=Transhumanism
gender.female=female
page.magic.section.metamagic=Metamagic
page.combat.section.ammo=Ammunition
page.augmentation.section.cyberware=Cyberware
page.augmentation.section.essence.acclimation.tooltip=Change level of the "Augmentation Acclimation" quality.\nProvides 0.1 essence hole per level.
page.skills.section.signature=Signature Maneuvers
page.combat.section.melee=Melee Weapons
page.life.title=Life
page.basicdata.section.attributes.title=Attributes
page.magic.section.adeptpowers=Adept Powers
label.mode.chargen=Creation Mode
page.skills.section.knowledge=Knowledge skills
page.combat.section.ranged=Ranged Weapons
error.title=Drek
page.augmentation.section.essence=Essence
action.conversionDecrease=Convert less Karma to Nuyen
label.heat=Heat
label.magicOrResonance=Magic/Resonance
label.gender=Gender
page.skills.title=Skills
label.realname=Real name
action.conversionIncrease=Convert more Karma to Nuyen
page.augmentation.section.essence.acclimation=Acclimation Level
gender.male=male
label.mode.career=Career Mode
page.vehicles.section.vehicles=Vehicles
error.continuingCreation=Failed to open the character and continue creation.\nThis is a bug in the application you can report, but the character is likely beyond saving.
page.gear.section.other=Other
gender.diverse=diverse
page.matrix.section.persona=Persona
page.life.section.lifestyles=Lifestyles
page.skills.section.language=Languages
page.matrix.section.accessories=Accessories
page.magic.title=Magic
page.augmentation.title=Augmentation
page.augmentation.section.essence.essHole=Essence hole
label.nuyen=Nuyen
label.karma=Karma
page.matrix.heading.device=Device
