generator.name=Karma System
generator.desc=Houserule

attrib.adjust.noSpecialAttribute=Not a special attribute
attrib.adjust.notEnoughCP=Not at least 4 CP
attrib.adjust.already12CP=Already 12 CP converted

attrib.attrib.noCharacterAttribute=Not a character attribute
attrib.attrib.already20CP=Already 20 CP converted
attrib.attrib.notEnoughCP=Need at least 2 CP

pointbuy.todo.metatype=No metatype selected
pointbuy.todo.skills.too_many_converted=Too many (%d) CP converted to skill points
pointbuy.todo.attrib.too_many_regular=Too many (%d) CP converted to regular attributes
pointbuy.todo.attrib.too_many_special=Too many (%d) CP converted to special attributes