explain.skill_not_untrained=%s not usable untrained
label.variant.standard=Standard
impossible.choiceMissing=Choice missing
label.variant=Variant
explain.untrained_skill=%s is untrained
label.wifiadvantage=WiFi Advantage
require.negate=No
label.pool=Pool
label.accessories=Accessories
label.rating=rating

