rule.chargen_raise_above_6=Allow MAG/RES>6 by initiation/submersion
rule.chargen_extended_contact=Use extended contact rules (6WC)
rule.chargen_max_transhuman=Max. transhumanism grade at CharGen
rule.chargen_negative_nuyen=Allow to temporarily have negative Nuyen
rule.chargen_prio_adept_pp.prio_magic=Powerpoints only from priorities
rule.allow_transhumanism=Allow Transhumanism
rule.allow_neuromorphism=Allow Neuromorphism
rule.allow_used_cultured_bioware=Allow used cultured bioware
rule.chargen_max_initiation=Max. initiation grade at CharGen
rule.chargen_max_submersion=Max. submersion grade at CharGen
rule.chargen_adjustment_on_lowered_max=Adjustmentpoints usuable for attributes with lowered max
rule.chargen_prio_adjusted_magic_reso=Use adjusted MAG/RES
rule.chargen_max_availability=Maximum availability during chargen
rule.chargen_buy_spells_karma=Allow buying spells / complex forms with adjustment Karma
rule.add_strength_to_melee_ar=Add STR to melee attack rating
rule.high_strength_adds_damage=Strength increases melee combat damage
rule.chargen_more_knowledge=Have LOG + INT knowledge skills
rule.mystadept_advance_raise_magic_raise_pp=Mystic Adept: Raising MAG raises PP
rule.cargofactor_is_without_seats=(Factory default) Seats occupy cargo factor
rule.chargen_errated_point_buy=Use errated Point Buy resource rules
rule.always_ask_for_flags=Always ask for item flags