explain.expertise=Expert.
explain.skill_not_untrained=%s not usable untrained
explain.specialization=Special.
explain.untrained_skill=%s is untrained
impossible.choiceMissing=Choice missing
label.accessories=Accessories
label.adeptpower=Power
label.draketype=Drake Type
label.dracogenesis=Dracogenesis
label.echo=Echo
label.essencehole_for=Essence hole for %s
label.metamagic=Metamagic
label.or=Or
label.pool=Pool
label.rating=rating
label.variant.standard=Standard
label.variant=Variant
label.wifiadvantage=WiFi Advantage
modification.allow.complex_form=Allow Complex Form '%s'
modification.allow.skill=Activate skill '%s'
modification.allow.skill_choice=Allow chosen skill
modification.check.attribute=for all tests based upon %s.
modification.check.dice=Add %s dice
modification.check.edge_boost=Edge Boosts cost %s
modification.check.edge_cost=Edge Boosts cost %s less
modification.check.edge_temporary=%s temporary Edge
modification.check.edge=%s lasting Edge
modification.check.not_earn_edge=Can not earn edge
modification.check.for=for
modification.choice.attribute=selected attribute
modification.choice.quality=selected quality
modification.choice.skill=selected skill
modification.choice.drain_mage=Drain Mage
modification.choice.drain_adept=Drain Adept
modification.choice.gear=Gear
modification.choice.program=Program
modification.choice.adept_power=Adept Power
modification.choice.spell=Select a spell
modification.conditional=conditional
modification.allow.contact_type=Allow contact type '%s'
modification.contact_type_points=%s contact points: %s
modification.creation_points.adjust=Adjustment Karma: %s
modification.creation_points.adjust_drake=Drake Adjustment Karma: %s
modification.creation_points.attributes=Attribute points: %s
modification.creation_points.character_points=Character points: %s
modification.creation_points.contact_points=Contact points: %s
modification.creation_points.lifepath_modules=Life modules: %s
modification.creation_points.maxed_out_attributes=Max attributes
modification.creation_points.maxed_out_skills=Max skills
modification.creation_points.nuyen=Nuyen: %s
modification.creation_points.skills=Skill points: %s
modification.critterpower=Critter Power ''%s''
modification.forbid.contact_type=Forbid contact type '%s'
modification.forbid.complex_form=Forbid Complex Form '%s'
modification.forbid.skill=Forbid skill '%s' at creation
modification.forbid.skill_choice=Forbid selected skill at creation
modification.forbid.magicreso=Cannot pick '%s'
modification.hook.withCap=Allow %s %s accessories
modification.hook.withoutCap=Allow %s accessories
modification.magicreso=(Digital) Awakened '%s'
modification.skill.item=associated skill
modification.license=License
modification.quality=Quality ''%s''
modification.rating=Rtg.
modification.relevance.combat=Relevant for combat
modification.relevance=Relevant for %s
modification.sin=SIN
modification.skill=Skill '%s'
modification.value.initiation_rank=Initiation Rank
modification.value.level=level
require.negate=No
requirement.choice.skill=selected skill %s or better
