explain.skill_not_untrained=%s not usable untrained
explain.untrained_skill=%s is untrained
explain.specialization=Special.
explain.expertise=Expert.
impossible.choiceMissing=Choice missing
label.accessories=Accessories
label.adeptpower=Power
label.draketype=Drake Type
label.pool=Pool
label.rating=rating
label.variant.standard=Standard
label.variant=Variant
label.wifiadvantage=WiFi Advantage
modification.allow.skill=Activate skill '%s'
modification.check.dice=Add %s dice
modification.check.edge_boost=Edge Boosts cost %s
modification.check.edge_temporary=%s temporary Edge
modification.check.edge_cost=Edge Boosts cost %s less
modification.check.for=for
modification.check.attribute=for all tests based upon %s.
modification.choice.attribute=selected attribute
modification.choice.skill=selected skill
modification.critterpower=Critter Power ''%s''
modification.conditional=conditional
modification.quality=Quality ''%s''
modification.hook.withCap=Allow %s %s accessories
modification.hook.withoutCap=Allow %s accessories
modification.value.level=level
require.negate=No
requirement.choice.skill=selected skill %s or better