<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>shadowrun6-master</artifactId>
		<version>0.0.2-SNAPSHOT</version>
	</parent>
	<artifactId>shadowrun6-data</artifactId>
	<name>SR6_Data</name>

	<properties>
		<maven.deploy.skip>false</maven.deploy.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>simple-persist</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-rules</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun-common-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-core</artifactId>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jpl</artifactId>
			<scope>test</scope>
		</dependency>
 		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.0.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
       		<groupId>org.apache.maven.plugins</groupId>
       		<artifactId>maven-checkstyle-plugin</artifactId>
       		<version>3.3.0</version>
       		<configuration>
		   		<excludes>**/module-info.java</excludes>
		         <consoleOutput>true</consoleOutput>
        			<failsOnError>true</failsOnError>
         		<linkXRef>false</linkXRef>
         		<checkstyleRules>
            		<module name="Checker">
              			<module name="Translation">
    							<property name="fileExtensions" value=".properties"/>
    							<property name="requiredTranslations" value="en,de,fr"/>
  			  				</module>
            		</module>
          		</checkstyleRules>
       		</configuration>
       		<executions>
         		<execution>
           			<id>validate</id>
           			<phase>validate</phase>
           			<goals>
             			<goal>check</goal>
           			</goals>
         		</execution>
       		</executions>
     	</plugin>

		</plugins>
	</build>

	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
		</repository>
	</distributionManagement>
</project>