<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>shadowrun6-master</artifactId>
		<version>0.0.2-SNAPSHOT</version>
	</parent>
	<artifactId>shadowrun6-print</artifactId>
	<name>SR6_Print</name>

	<dependencies>
		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>simple-persist</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-rules</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun-common-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-data</artifactId>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>itextpdf</artifactId>
			<version>4.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcmail-jdk15on</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bctsp-jdk15on</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcprov-jdk15on</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>
