page.skills.title=Skills
page.skills.section.normal=Normal skills
page.skills.section.knowledge=Knowledge skills
page.skills.section.language=Languages
page.skills.section.signature=Signature Maneuvers