choice.magician_adept=Which advantages do you want?
explain=You need to make some choices for the selection.
choice.adept=Choice for adept
choice.magician=Choice for magician
label.chemical=Chemical
label.rating=Rating
label.variant=Variant
variant.regular=Regular
title=Select options for '%s'

selector.skill.title=Choose a skill to add