page.title=Metatype

tab.data=Data
tab.description=Description
tab.custom=Choose

button.roll=Random
label.gender=Gender
label.size=Size
label.size.tail=cm
label.weight=Weight
label.weight.tail=kg
label.bodytype=This will be a

gender.male=male
gender.female=female
gender.diverse=diverse

bodytype.metahuman=Normal Metatype
bodytype.shapeshifter=Shapeshifter
bodytype.drake=Drake (Aware)
bodytype.drake_latent=Drake (Latent)