bodytype.drake=Drake (Aware)
bodytype.drake_latent=Drake (Latent)
bodytype.metahuman=Normal Metatype
bodytype.shapeshifter=Shapeshifter
button.roll=Random
confirm.cancel.mess=Do you really want to cancel character creation?
confirm.cancel.title=Really cancel
gender.diverse=diverse
gender.female=female
gender.male=male
label.bodytype=This will be a
label.essence=Essence
label.gender=Gender
label.karma=Karma
label.nuyen=Nuyen
label.pointbuy.cp=CP
label.size.tail=cm
label.size=Size
label.weight.tail=kg
label.weight=Weight
page.adeptpowers.convertCP=CP converted to PP
page.adeptpowers.sort.tooltip=Sort alphabetically or by cost
page.adeptpowers.search.prompt=Search Keyword
page.adeptpowers.convertFree=Power Points
page.drake.title=Dracomorphosis
page.drake.placeholder.available=You think you are a drake?\nDream on!
page.drake.placeholder.selected=Feeble drake! You should work on yourself!
page.drake.level=Dracogenesis rank:
page.gear.converted=Karma converted to
page.gear.intro=You can pick important gear pieces on this page to get a better overview over required Nuyen.\nOnce you finish the assistant, you can still finetune your equipment.
page.gear.nuyen=Nuyen
page.gear.placeholder.available=I cannot find any gear that matches your search criteria.
page.gear.placeholder.selected=You have money - buy some nice things.
page.gear.rule.ignoreGearRequirements=Allow buying gear even when requirements are not met
page.gear.rule.showAutoAdded=Show gear that has been added by other choices and cannot be modified
page.gear.title=Gear
page.mortypecell.cost=%d CP
page.mortypecell.karma=%d
page.qualities.numQualities=Count:
page.skills.head.points2=Knowledge
page.skills.head.points=Points
page.skills.head.pointbuy_converted=Conv.CP
page.title=Metatype
quality.search.prompt=Search keyword
quality.sort.tooltip=Change sort order
quality.what.all=All
quality.what.negative=Negative Qualities
quality.what.positive=Positive Qualities
tab.custom=Choose
tab.data=Data
tab.description=Description

page.surge.title=SURGE
page.surge.placeholder.available=No metagenic qualities available for this character
page.surge.placeholder.selected=You are no freak yet - perhaps it better stays this way.
page.surge.pointsSpent=Karma for SURGE:

