label.size=Size
label.weight.tail=kg
label.gender=Gender
page.title=Metatype
gender.male=male
bodytype.drake_latent=Drake (Latent)
gender.female=female
gender.diverse=diverse
label.size.tail=cm
label.bodytype=This will be a
bodytype.metahuman=Normal Metatype
tab.data=Data
tab.custom=Choose
button.roll=Random
label.weight=Weight
bodytype.drake=Drake (Aware)
tab.description=Description
bodytype.shapeshifter=Shapeshifter
