page.gear.intro=You can pick important gear pieces on this page to get a better overview over required Nuyen.\nOnce you finish the assistant, you can still finetune your equipment.
page.gear.converted=Karma converted to
AdeptPower.search.prompt=Search Keyword
quality.what.all=All
page.gear.nuyen=Nuyen
quality.what.negative=Negative Qualities
quality.sort.tooltip=Change sort order
page.gear.placeholder.available=I cannot find any gear that matches your search criteria.
page.skills.head.points=Points
page.gear.rule.ignoreGearRequirements=Allow buying gear even when requirements are not met
page.gear.placeholder.selected=You have money - buy some nice things.
page.qualities.numQualities=Count:
quality.search.prompt=Search keyword
page.skills.head.points2=Knowledge
label.nuyen=Nuyen
label.karma=Karma
page.gear.title=Gear
quality.what.positive=Positive Qualities
label.essence=Essence

confirm.cancel.title=Really cancel
confirm.cancel.mess=Do you really want to cancel character creation?