page.title=SURGE
placeholder.available=No metagenic qualities available for this character
placeholder.selected=You are no freak yet - perhaps it better stays this way.
quality.search.prompt=Search keyword
quality.what.all=All
surge.pointsSpent=Karma for SURGE:
quality.what.positive=Positive Qualities
quality.what.negative=Negative Qualities
quality.sort.tooltip=Change sort order
