page.title=SURGE

placeholder.available=No metagenic qualities available for this character
placeholder.selected=You are no freak yet - perhaps it better stays this way.

quality.what.all=All
quality.what.positive=Positive Qualities
quality.what.negative=Negative Qualities
quality.sort.tooltip=Change sort order
quality.search.prompt=Search keyword

surge.pointsSpent=Karma for SURGE: