wizard.page.lifepath1.title=Born this way
wizard.page.lifepath1.nationality=Nationality
wizard.page.lifepath1.language=Native Language
wizard.page.lifepath1.mortype=Magic or Resonance
wizard.page.lifepath1.tradition=Tradition
wizard.page.lifepath1.aspect=Aspect
wizard.page.lifepath1.button_quality=Select
wizard.page.lifepath1.quality1=Select a quality
wizard.page.lifepath1.quality2=and optionally an opposing quality
