wizard.selectGenerator.title=Wähle Erschaffungsart

generator.PriorityCharacterGenerator=Prioritätensystem

generator.PriorityCharacterGenerator.line2=Ideal für Einsteiger

generator.PriorityCharacterGenerator.desc=Das normale Erschaffungssystem für Shadowrun
