page.title=Metatyp

tab.data=Daten
tab.description=Beschreibung
tab.custom=Wähle

button.roll=Zufällig
label.gender=Geschlecht
label.size=Größe
label.size.tail=cm
label.weight=Gewicht
label.weight.tail=kg
#label.skin=Haut/Fellfarbe
#label.hair=Haarfarbe
#label.eyes=Augenfarbe

gender.male=männlich
gender.female=weiblich
gender.diverse=divers