<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>shadowrun6-master</artifactId>
		<version>0.0.3-SNAPSHOT</version>
	</parent>

	<groupId>org.prelle.rpgframework</groupId>
	<artifactId>shadowrun6-export-json</artifactId>
	<name>Shadowrun 6 Export JSON</name>
	<description>Shadowrun 6 for Genesis</description>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

	<organization>
		<name>Anja Prelle</name>
		<url>http://www.rpgframework.de/</url>
	</organization>

	<dependencies>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-foundry</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.10.1</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-rules</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun-common-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-data</artifactId>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jpl</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<developers>
		<developer>
			<name>Stefan Prelle</name>
			<email>stefan@rpgframework.de</email>
			<timezone>GMT+1</timezone>
			<roles>
				<role>Lead developer</role>
			</roles>
		</developer>
	</developers>

	<licenses>
		<license>
			<name>No License</name>
		</license>
	</licenses>
</project>
