chargen.LifePathCharacterGenerator.desc=The Life Path system provides an alternative to character creation in which you choose which experiences and events make up your character\u2019s history and background. These choices provide you with various options to choose your starting attributes, skills, resources, and contacts.
chargen.LifePathCharacterGenerator=Life Path System

chargen.PointBuyCharacterGenerator.desc=Use the Point Buy system when you want to make a highly customized character and don\u2019t mind spending some extra time working out the points to get it just the way you want it.
chargen.PointBuyCharacterGenerator=Point Buy System

chargen.PriorityCharacterGenerator.desc=This is the regular generation system from the Core rules.
chargen.PriorityCharacterGenerator=Priority System

chargen.SumToTenCharacterGenerator.desc=If you\u2019re looking for a little extra customization than the priority system allows you to achieve, Sum-to-Ten is an easy alternative. Sum-to-Ten is a modified approach to the priority system.
chargen.SumToTenCharacterGenerator=Sum to Ten System

impossible.qualityAlready6=Already 6 qualities selected
impossible.remainingAdjustmentPoints=%d adjustment points left
impossible.remainingKnowledgePoints=%d knowledge skill/languages left
impossible.remainingSkillPoints=%d skill points left

todo.powerPointsLeft=%.2f unspent Power Points
