chargen.PointBuyCharacterGenerator=Point Buy System 
chargen.PriorityCharacterGenerator=Priority System
chargen.LifeModulesCharacterGenerator=Lifemodule System
chargen.SumToTenCharacterGenerator=Sum to Ten System