impossible.qualityAlready6=Already 6 qualities selected
impossible.tooManyQualities=You have more than 6 qualites
impossible.gainedMoreThan20Karma=Reduce bonus Karma from negative qualities
impossible.remainingAdjustmentPoints=%d adjustment points left
impossible.remainingKnowledgePoints=%d knowledge skill/languages left
impossible.remainingSkillPoints=%d skill points left
impossible.ratingExceedsResonance=Rating exceeds Resonance
impossible.sumRatingsExceedsMax=Integration pool full - max %d allowed
impossible.sumForceExceedsMax=New sum of force ratings %d would exceed %d

todo.lifepath.born.quality.missing=Select a quality you were born with
todo.lifepath.languageNotSet=Select your native language
todo.shifter_must_have_magic=Shapeshifter must have magic attribute
todo.shifter_must_be_metahuman=Only metahumans can be shapeshifters