impossible.qualityAlready6=Already %d qualities selected
impossible.tooManyQualities=You have more than %d qualities
impossible.gainedMoreThan20Karma=Reduce bonus Karma from negative qualities to %d
impossible.remainingAdjustmentPoints=%d adjustment points left
impossible.remainingKnowledgePoints=%d knowledge skill/languages left
impossible.remainingSkillPoints=%d skill points left
impossible.ratingExceedsResonance=Rating exceeds Resonance
impossible.sumRatingsExceedsMax=Integration pool full - max %d allowed
impossible.sumForceExceedsMax=New sum of force ratings %d would exceed %d
impossible.qualityMoreThan20Karma=Reduce bonus Karma from negative qualities
impossible.cannotMaxMoreAttributes=Cannot maximize more attributes
impossible.remainingAttributePoints=%d attribute points left
impossible.spentMoreThan30SURGE=Spend more than 30 karma on SURGE
impossible.tooManySpells=Too many spells
impossible.tooManyComplexForms=Too many complex forms
impossible.cannotBindMoreFoci=Cannot bind more foci
impossible.focusExceedsMagic=Focus exceeds magic
impossible.sumForceExceedsMax=Sum of force exceeds max
impossible.cannotBindMoreDataStructures=Cannot bind more data structures
impossible.ratingExceedsResonance=Rating exceeds resonance
impossible.sumRatingsExceedsMax=Sum or ratings exceeds max

todo.lifepath.born.quality.missing=Select a quality you were born with
todo.lifepath.languageNotSet=Select your native language
todo.shifter_must_have_magic=Shapeshifter must have magic attribute
todo.shifter_must_be_metahuman=Only metahumans can be shapeshifters
todo.lifepath.child.quality.missing=Lifepath child quality missing
todo.lifepath.childAreaNotSet=Lifepath child area knowledge not defined
todo.lifepath.early.skill.missing=Lifepath early skill missing
todo.lifepath.early.attribute.missing=Lifepath early attribute missing
todo.lifepath.modules.notEnough=Select more adult life modules
todo.lifepath.modules.tooMany=Too many adult life modules selected
impossible.lifepath.moduleLimit=You may select up to %d life path modules and may not select the same module more than twice
impossible.lifepath.moduleRequired=Cannot remove this life module because it is required by: %s
impossible.requirementsNotMet=Requirements not met
