impossible.qualityAlready6=Already 6 qualities selected
impossible.tooManyQualities=You have more than 6 qualites
impossible.remainingAdjustmentPoints=%d adjustment points left
impossible.remainingKnowledgePoints=%d knowledge skill/languages left
impossible.remainingSkillPoints=%d skill points left
impossible.ratingExceedsResonance=Rating exceeds Resonance
impossible.sumRatingsExceedsMax=Integration pool full - max %d allowed