chargeninfo.generator=Creation rules used: %s
chargeninfo.no_generator=No generator info stored in character
chargeninfo.prio=Priority picks
chargeninfo.prio.metatype=Meta: %s
chargeninfo.prio.attribute=Attrib: %s
chargeninfo.prio.magic=Magic/Resonance: %s
chargeninfo.prio.skills=Skills: %s
chargeninfo.prio.resources=Resrc: %s
chargeninfo.prio.mysadpp=MAG invested into %d power points
chargeninfo.conversion.nuyen=%d Karma have been converted to Nuyen
chargeninfo.conversion.contacts=%d Karma for contact points