chargeninfo.prio.mysadpp=MAG invested into %d power points
chargeninfo.generator=Creation rules used: %s
chargeninfo.conversion.contacts=%d Karma for contact points
chargeninfo.no_generator=No generator info stored in character
chargeninfo.prio=Priority picks
chargeninfo.prio.magic=Magic/Resonance: %s
chargeninfo.prio.metatype=Meta: %s
chargeninfo.prio.attribute=Attrib: %s
chargeninfo.prio.skills=Skills: %s
chargeninfo.prio.resources=Resrc: %s
chargeninfo.conversion.nuyen=%d Karma have been converted to Nuyen

chargeninfo.pointbuy.adjust=%d CP converted to %d adjustment points.
chargeninfo.pointbuy.attrib=%d CP converted to %d attribute points.
chargeninfo.pointbuy.skill=%d CP converted to %d skill points.
chargeninfo.pointbuy.ppoints=%d CP und %d Karma for power points
chargeninfo.pointbuy.resrc=%d CP converted to %d Nuyen
chargeninfo.pointbuy.spells=%d CP and %d Karma for spells & rituals