skill.error.specNotAvailable=Skill '%s' has no available specialization '%s'
column.points1=Pt.
column.points2=Ka.
skill.error.maxSkillsMaxed=You may not raise more than %d skills to maximum.
label.native_language=Native Language

pointbuy.points1=Skill Points
pointbuy.points2=Karma
