column.points1=Pt.
column.points2=Ka.
column.points3=Ka.
label.native_language=Native Language
pointbuy.points1=Skill Points
pointbuy.points2=Karma
skill.error.maxSkillsMaxed=You may not raise more than %d skills to maximum.
skill.error.specNotAvailable=Skill '%s' has no available specialization '%s'
skill.error.exoticWithoutSpec=Select a free specialization for "Exotic Weapons" 
