column.points1=Points
column.points2=Karma
column.points3=Karma
label.native_language=Native Language
pointbuy.points1=Points
pointbuy.points2=Karma
skill.error.maxSkillsMaxed=You may not raise more than %d skills to maximum.
skill.error.specNotAvailable=Skill '%s' has no available specialization '%s'
skill.error.exoticWithoutSpec=Select a free specialization for "Exotic Weapons" 
