rule.chargen_adjustment_on_lowered_max=Adjustmentpoints usuable for attributes with lowered max
rule.chargen_prio_adept_pp=Mystic Adept Power Points in PrioGen 
rule.chargen_prio_adept_pp.final_magic=Prio+Adjust+Karma
rule.chargen_prio_adept_pp.magic_plus_karma=Prio + Karma
rule.chargen_prio_adept_pp.prio_magic=Priority only
rule.chargen_allow_legal_avail7plus=Allow buying legal gear with availability 7+
rule.chargen_buy_spells_karma=Allow buying spells / complex forms with adjustment Karma
rule.allow_transhumanism=Allow Transhumanism
rule.chargen_extended_contact=Use extended contact rules (6WC)