<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>shadowrun6-master</artifactId>
		<version>0.0.2-SNAPSHOT</version>
	</parent>

	<groupId>de.rpgframework.shadowrun6</groupId>
	<artifactId>commlink6</artifactId>
	<version>0.10.1</version>
	<packaging>jar</packaging>

	<name>Commlink6</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>17</maven.compiler.release>
		<javafx.version>19</javafx.version>
		<maven.skip.deploy>true</maven.skip.deploy>
		<maven.skip.install>true</maven.skip.install>
		<javafx.plugin.version>0.0.8</javafx.plugin.version>
		<client.plugin.version>1.0.16</client.plugin.version>
		<attach.version>4.0.17-SNAPSHOT</attach.version>
		<rpgfw.version>5.0.2-SNAPSHOT</rpgfw.version>
		<mainClassName>de.rpgframework.shadowrun6.comlink.ComLinkStarter</mainClassName>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-base</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<!-- Attach -->
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>browser</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>device</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>display</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>settings</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>statusbar</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>storage</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>util</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<!--dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>attach-pdf</artifactId>
			<version>${rpgfw.version}</version>
		</dependency-->


		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>javafx-extensions</artifactId>
			<version>[5.0.2-SNAPSHOT,)</version>
			<exclusions>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-swing</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>eden-client</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>eden-client-jfx</artifactId>
			<version>0.0.4-SNAPSHOT</version>
		</dependency>
      <dependency>
        <groupId>org.prelle</groupId>
        <artifactId>simple-persist</artifactId>
        </dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-javafx</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-rules</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-chargen</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-chargen-jfx</artifactId>
			<version>0.0.2-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-data</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>shadowrun6-export-pdf</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<!--dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>shadowrun6-export-fvtt</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency-->
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>shadowrun6-export-json</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>jfrog</id>
			<url>https://rpgframework.jfrog.io/artifactory/RPGFramework</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.5.0</version>

				<configuration>
					<descriptors>
						<descriptor>src/assembly/src.xml</descriptor>
					</descriptors>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>de.rpgframework.shadowrun6.comlink.ComLinkStarter</mainClass>
						</manifest>
					</archive>
				</configuration>

				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>

			</plugin>
		</plugins>
	</build>

</project>
