<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>shadowrun6-master</artifactId>
		<version>0.0.3-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<groupId>de.rpgframework.shadowrun6</groupId>
	<artifactId>commlink6</artifactId>
	<version>1.7.3-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>Commlink6</name>
	<description>Shadowrun 6 character management application</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<javafx.version>20.0.1</javafx.version>
		<maven.deploy.skip>false</maven.deploy.skip>
		<maven.install.skip>false</maven.install.skip>
		<javafx.plugin.version>0.0.8</javafx.plugin.version>
		<client.plugin.version>1.0.24</client.plugin.version>
		<attach.version>4.0.21</attach.version>
		<rpgfw.version>5.2.0</rpgfw.version>
	</properties>
	<!-- Comment for no real purpose -->

	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-base</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-swing</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<!-- Attach -->
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>browser</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>device</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>display</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>settings</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>statusbar</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>storage</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>com.gluonhq.attach</groupId>
			<artifactId>util</artifactId>
			<version>${attach.version}</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>attach-pdf</artifactId>
			<version>${rpgfw.version}</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>de.rpgframework</groupId>-->
<!--			<artifactId>attach-pdf-pdfbox</artifactId>-->
<!--			<version>${rpgfw.version}</version>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.controlsfx</groupId>
			<artifactId>controlsfx</artifactId>
			<version>11.1.2</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.32</version>
			<scope>provided</scope>
		</dependency>


		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>javafx-extensions</artifactId>
			<version>[5.1.0-SNAPSHOT,)</version>
			<exclusions>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-swing</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>eden-client</artifactId>
			<version>0.1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>eden-client-jfx</artifactId>
			<version>0.0.6-SNAPSHOT</version>
		</dependency>
      <dependency>
        <groupId>org.prelle</groupId>
        <artifactId>simple-persist</artifactId>
        </dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-javafx</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-rules</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-core</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-chargen</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-chargen-jfx</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-data</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>shadowrun6-export-pdf</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>shadowrun6-export-fvtt</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>shadowrun6-export-json</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.5.0</version>

				<configuration>
					<descriptors>
						<descriptor>src/assembly/src.xml</descriptor>
					</descriptors>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>de.rpgframework.shadowrun6.comlink.ComLinkStarter</mainClass>
						</manifest>
					</archive>
				</configuration>

				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.prelle</groupId>
				<artifactId>update4j-plugin</artifactId>
				<version>1.0-SNAPSHOT</version>
				<configuration>
					<baseUri>https://eden.rpgframework.de/</baseUri>
					<basePath>${user.home}/CommLink6/app/STABILITY</basePath>
					<launcher>de.rpgframework.shadowrun6.updater.CommlinkLauncher2</launcher>
					<osHandling>ALL</osHandling>
					<properties>
						<property>
							<key>default.launcher.main.class</key>
							<value>de.rpgframework.shadowrun6.comlink.ComLinkStarter</value>
						</property>
						<property>
							<key>default.launcher.system.project.version</key>
							<value>${project.version}</value>
						</property>
					</properties>
					<includes>
						<include>
							<comment>Main Shadowrun content</comment>
							<url>http://eden.rpgframework.de/commlink6-updates/${project.artifactId}-${project.version}-complete.jar</url>
							<path>${project.build.directory}/${project.artifactId}-${project.version}-complete.jar</path>
						</include>
					</includes>
					<excludes>
						<exclude>de.rpgframework.shadowrun6:commlink6</exclude>
						<exclude>org.prelle:javafx-extensions</exclude>
						<exclude>org.prelle:simple-persist</exclude>
						<exclude>de.rpgframework:eden-api</exclude>
						<exclude>de.rpgframework:eden-client</exclude>
						<exclude>de.rpgframework:eden-client-jfx</exclude>
						<exclude>de.rpgframework:rpgframework-core</exclude>
						<exclude>de.rpgframework:rpgframework-rules</exclude>
						<exclude>de.rpgframework:rpgframework-javafx</exclude>
						<exclude>de.rpgframework:rpgframework-generator</exclude>
						<exclude>de.rpgframework:itextpdf</exclude>
						<exclude>de.rpgframework:attach-pdf</exclude>
						<!--exclude>de.rpgframework:attach-pdf-pdfbox</exclude-->
						<exclude>de.rpgframework:shadowrun-common-core</exclude>
						<exclude>de.rpgframework:shadowrun-common-chargen</exclude>
						<exclude>de.rpgframework:shadowrun-common-chargen-jfx</exclude>
						<exclude>de.rpgframework:shadowrun6-core</exclude>
						<exclude>de.rpgframework:shadowrun6-chargen</exclude>
						<exclude>de.rpgframework:shadowrun6-chargen-jfx</exclude>
						<exclude>de.rpgframework:shadowrun6-data</exclude>
						<exclude>org.prelle.rpgframework:shadowrun6-export-pdf</exclude>
						<exclude>org.prelle.rpgframework:shadowrun6-export-json</exclude>
						<exclude>de.rpgframework:shadowrun6-export-fvtt</exclude>
						<exclude>de.rpgframework:foundryvtt-documents</exclude>
						<exclude>de.rpgframework:shadowrun6-foundry</exclude>
					</excludes>
					<includeExtras>
						<includeExtra>com.gluonhq.attach:browser:4.0.19:desktop</includeExtra>
						<includeExtra>com.gluonhq.attach:display:4.0.19:desktop</includeExtra>
						<includeExtra>com.gluonhq.attach:settings:4.0.19:desktop</includeExtra>
						<includeExtra>com.gluonhq.attach:storage:4.0.19:desktop</includeExtra>
						<includeExtra>de.rpgframework:attach-pdf-pdfbox:5.1.5</includeExtra>
						<includeExtra>org.apache.pdfbox:pdfbox:3.0.1</includeExtra>
						<includeExtra>org.apache.pdfbox:pdfbox-io:3.0.1</includeExtra>
						<includeExtra>commons-logging:commons-logging:1.2</includeExtra>
						<includeExtra>org.apache.pdfbox:fontbox:3.0.1</includeExtra>
					</includeExtras>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<pluginRepositories>
		<pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
		<pluginRepository>
			<id>gluon-releases</id>
			<url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
		</pluginRepository>
	</pluginRepositories>

 	<distributionManagement>
   	<repository>
      	<id>github</id>
      	<name>GitHub Packages</name>
      	<url>https://maven.pkg.github.com/taranion/CommLink</url>
    	</repository>
  </distributionManagement>
</project>
